version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
      - AIRTABLE_TABLE_ID=${AIRTABLE_TABLE_ID}
    env_file:
      - .env
    volumes:
      - ./static:/app/static